
name: Create golang vendor dist
on:
  push:
    tags:
      - '**'

jobs:
  golang-dist:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create golang dist
        uses: projg2/golang-dist-action@v1
        with:
          dist-filename: zabbix-agent2-plugin-postgresql-7.0.30
          exclude-directories: 
          vendor-dir: zabbix-agent2-plugin-postgresql-7.0.30

